### ISSUE TITLE
RELEASE 1.2.0!

### ISSUE THREAD

**Issue by philippReist** [philippReist/DanceBotsEditor#102]
@tiemes @r-oung: I just released 1.2.0. I don't have a mac so it would be great if one of you could test the Mac auto-build release.

In particular, please check if there is an mp3_files folder with two mp3 files.

@tiemes Please also check the Win release to make sure it does not run just on my PC :) Once the tests are good, we can update the links on the dancebots.ch website. If you want to create a custom msi installer with additional MP3 files for workshops, I added the instructions to the main readme.

**Comment by philippReist** [comment]
FYI: The MP3 files should be copied by CMAKE to the release config build folder https://github.com/philippReist/DanceBotsEditor/blob/develop/gui/CMakeLists.txt#L73

**Comment by tiemes** [comment]
@philippReist Nice - thanks!
Where should I find the sample files in the mac version? I only see DanceBotsEditor. It opens, I can't find the files though.

**Comment by r-oung** [comment]
@philippReist I checked on both Windows 10 Pro and macOS 11.6:

- Windows: `mp3_files` folder is there with both MP3 files.
- macOS: `mp3_files` folder is missing from the package contents. I think the [macOS deploy script](https://github.com/philippReist/DanceBotsEditor/blob/develop/gui/mac_os_rc/deploy.sh) needs to be adjusted to copy these files over. Let me know if you need help with this as I need to prep a machine to build this project again.

I didn't really follow this discussion, but is there any particular reason why you want to include the MP3 files in the package and not online? If it's to make it easier for students to get started, then I'm not sure this solves the problem because it isn't really straightforward to find these files. Suggestion: when pressing "Load" it should open a file selection dialog window in the `mp3_files` folder (and consider renaming the `mp3_files` folder to `samples`. Otherwise, I would suggest just adding a download link in the about/help window.

The editor runs on both platforms. I only did a basic test, but I noticed that the app refreshes whenever you press `Robot` and `Human` -- not sure if that's a bug or by design.

**Comment by tiemes** [comment]
The goal would be to make it as easy as possible to start. I totally agree with you, that it should open the "sample" folder on the first click on "load".

**Comment by philippReist** [comment]
I can look into opening the file dialog for the sample folder. Renaming to samples is good, too. 1.2.1 here we come :(

> The editor runs on both platforms. I only did a basic test, but I noticed that the app refreshes whenever you press Robot and Human -- not sure if that's a bug or by design.

What do you mean @r-oung ? Changing from robot to human and the other way around needs to reset the audio on the player, so it has to stop and then possibly reparse the timeline and regenerate the signal, and then set the data on the output. Do you mean that?

**Comment by r-oung** [comment]
> What do you mean @r-oung ? Changing from robot to human and the other way around needs to reset the audio on the player, so it has to stop and then possibly reparse the timeline and regenerate the signal, and then set the data on the output. Do you mean that?

So I looked into it more closely. When you toggle between `Robot` and `Human`, there's a modal that says "Setting output sound for humans/Dancebots...". The "problem" is that it displays this so quickly that I thought it was a bug -- :laughing: . See attached video. I had to record the video at 240 FPS to catch this. I guess that means I'm using a super fast computer :wink: .

https://user-images.githubusercontent.com/44389573/144537236-c188c0e6-4395-49f5-9eee-99a7660d49b2.mp4

IMO I don't really think the modal is necessary (or show it long enough for someone to read it), but it's your call.

Also, I noticed that the `Artist` and `Title` metadata for the 2 samples are missing. Can this be included?

**Comment by philippReist** [comment]
Fixed:
1. I removed the modal popup when switching from robot to human and back.
2. The load dialogue now default points to the mp3_samples folder

@r-oung the load folder dialogue path is relative to the application root dir - could you please verify that this works on Mac and add the deploy copy script step you mentioned above?

Once we have this in place and tested, we can merge to master and finally deploy this!

**Comment by r-oung** [comment]
@philippReist Sure. Can I assume that this is all on the `develop` branch?

**Comment by philippReist** [comment]
Thank you! Yes on develop.

**Comment by r-oung** [comment]
@philippReist Done! I made a pre-release [here](https://github.com/philippReist/DanceBotsEditor/releases/tag/v1.2.1-dev) so that other's can test it if they want. I tested it on macOS 10.15 and macOS 11.6.

**Comment by philippReist** [comment]
Great thank you @r-oung! And enjoy the KFC!

I found one more little bug, of course, but fixed it and now pushed the 1.2.1 to master, so we should now have the release in the bag. Could you do one last check on the release package for Mac please?

@tiemes - we should have it now!

**Comment by r-oung** [comment]
@philippReist The release package works on macOS 10.15 and 11.6! It took a year to release 1.2, but it's finally done! 🙌 🥳 🎉

**Comment by philippReist** [comment]
Thank you @r-oung !!! Yeah, this was not a very quick thing. Let's see how 1.2 will do in the wild! @tiemes thanks for your help, too!
