### ISSUE TITLE
GUI Language Localization

### ISSUE THREAD

**Issue by philippReist** [philippReist/DanceBotsEditor#71]
Goal is to provide DE/EN/FR/IT language options.

Qt features language localization features. I am not familiar with them so I would have to learn it. I would suggest @robinhanhart and @tiemes take the lead here.

Should there be a toggle in the GUI?

**Comment by tiemes** [comment]
main question is - how much effort is it? It is not a must have but would be nice. Do you have any experience with it @robinhanhart ?

**Comment by robinhanhart** [comment]
@tiemes It should not be that much effort. Qt already has everything built in. The code is ready for translation as all the text in the code is in the form `qsTr("English")`

From what I read the process should look like this: https://wiki.qt.io/How_to_create_a_multi_language_application#Add_translations_to_the_project
1.  Let a QT function run over the code files and make a list of all the english texts in a translation file.
2. Translate the list of english words to german and other languages.
3. Create a language switcher in the GUI
4. Change some cmake setting to compile with the languages

Will give it a try maybe need some help from @philippReist

**Comment by philippReist** [comment]
Sounds good - let me know if you need help!

**Comment by tiemes** [comment]
@robinhanhart is this still a thing?

**Comment by robinhanhart** [comment]
@tiemes Technically it would work. I did have the basic work for translation in a local branch (compiling with the language files) Didn't get it to work completely.
The problem is there is quite a bit of english text hardcoded in the code and would be a couple hours work of changing everything. Just ran out of time on this one.

Maybe a call with @philippReist at some point. Maybe I'm missing something or there is an easier way.

**Comment by tiemes** [comment]
ok, English is fine.
